---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: webapp
    spec:
      terminationGracePeriodSeconds: 90
      imagePullSecrets:
      - name: ocir-secret
      containers:
      - image: alpine
        name: webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        livenessProbe:
          httpGet:
            path: /cities.json
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /cities.json
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
